# Auto-generated from Harvard PLL scraper
# Generated at: 2026-08-22T11:12:19.088403Z
# Total courses: 57

HARVARD_PLL_COURSES = [
  {
    "title": "Beethoven's 9th Symphony and the 19th Century Orchestra",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/first-nights-beethoven%E2%80%99s-9th-symphony-and-19th-century-orchestra",
    "level": "intermediate",
    "description": "Learn about Beethoven’s monumental 9th Symphony and forms of orchestral music.",
    "duration": "3 weeks long",
    "topics": [
      "Art & Design",
      "Music",
      "Culture"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:53.110560Z"
  },
  {
    "title": "Introduction to Data Wise: A Collaborative Process to Improve Learning &amp; Teaching",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/introduction-data-wise-collaborative-process-improve-learning-teaching",
    "level": "intermediate",
    "description": "Learn what is involved in using data wisely to build a culture of collaborative inquiry.&nbsp;",
    "duration": "8 weeks long",
    "topics": [
      "Education & Teaching",
      "Education",
      "K–12",
      "Teaching"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 209.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "1 - 2 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:53.375825Z"
  },
  {
    "title": "Handel's Messiah and Baroque Oratorio",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/first-nights-handel%E2%80%99s-messiah-and-baroque-oratorio",
    "level": "intermediate",
    "description": "Discover Handel’s Messiah in this installment of First Nights, which will explore five masterpieces of western music.",
    "duration": "2 weeks long",
    "topics": [
      "Art & Design",
      "Music",
      "Culture"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:54.148433Z"
  },
  {
    "title": "Managing Happiness",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/managing-happiness",
    "level": "intermediate",
    "description": "Happiness is within your control. Write your own ending.",
    "duration": "3 weeks long",
    "topics": [
      "Business",
      "Leadership",
      "Management",
      "Workplace Culture"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 219.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 3 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:54.407815Z"
  },
  {
    "title": "Ciencia de Datos: Fundamentos de R",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/ciencia-de-datos-fundamentos-de-r",
    "level": "intermediate",
    "description": "Sentar las bases de conocimiento en R y aprender a discutir, analizar y visualizar datos.",
    "duration": "4 weeks long",
    "topics": [
      "Data Science"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 119.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 4 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:54.677962Z"
  },
  {
    "title": "Stem Cell Medicine: Parkinson's Disease",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/stem-cell-medicine-parkinsons-disease",
    "level": "intermediate",
    "description": "Equipping clinicians with an up‑to‑date, comprehensive understanding of stem cell–based approaches for Parkinson’s disease, including biological rationale, current trial outcomes, comparison with existing therapies, and guidance for evidence.",
    "duration": "self-paced",
    "topics": [
      "Health & Medicine",
      "Health",
      "Medicine",
      "Diseases",
      "Healthcare",
      "Medical Research"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2026-03/Parkinson%20Disease.jpg.webp?itok=1f1L6pKW",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:54.949529Z"
  },
  {
    "title": "Global Health Case Studies from a Biosocial Perspective",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/global-health-case-studies-biosocial-perspective",
    "level": "intermediate",
    "description": "Reimagine global health problems with some of the leading global health thinkers and actors through a case-based biosocial framework.",
    "duration": "8 weeks long",
    "topics": [
      "Health & Medicine",
      "Health",
      "Global Health",
      "Public Health",
      "Ethics",
      "Humanities"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "4 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:55.223841Z"
  },
  {
    "title": "CS50's Introduction to 2D Game Development",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/cs50s-introduction-2d-game-development",
    "level": "intermediate",
    "description": "Learn about the development of 2D and 3D interactive games in this hands-on course, as you explore the design of games such as Super Mario Bros., Pokémon, Angry Birds, and more.",
    "duration": "12 weeks long",
    "topics": [
      "Programming",
      "Art & Design",
      "Business"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 299.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "6 - 9 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:55.489893Z"
  },
  {
    "title": "CS50's Introduction to Cybersecurity",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/cs50s-introduction-cybersecurity",
    "level": "intermediate",
    "description": "Learn how to protect your own data, devices, and systems from today's threats.",
    "duration": "5 weeks long",
    "topics": [
      "Computer Science",
      "Cybersecurity",
      "Social Sciences",
      "Business"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 6 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:55.747792Z"
  },
  {
    "title": "Data Science: Building Machine Learning Models",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/data-science-building-machine-learning-models",
    "level": "intermediate",
    "description": "Build a movie recommendation system and learn the science behind one of the most popular and successful data science techniques.",
    "duration": "8 weeks long",
    "topics": [
      "Computer Science",
      "Machine Learning",
      "Algorithms",
      "Data Science"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 4 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:56.019604Z"
  },
  {
    "title": "Strategic Finance for Nonprofit Leaders",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/strategic-finance-nonprofit-leaders",
    "level": "intermediate",
    "description": "Designed for current and aspiring nonprofit leaders, this course helps learners build the confidence needed to make stronger financial decisions in mission-driven organizations.",
    "duration": "6 weeks long",
    "topics": [
      "Business",
      "Finance",
      "Leadership",
      "Management",
      "Strategic Management",
      "Government",
      "Social Sciences"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 199.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 3 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:56.278526Z"
  },
  {
    "title": "Buddhism Through Its Scriptures",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/buddhism-through-its-scriptures",
    "level": "intermediate",
    "description": "Learn about the rich and diverse beliefs and practices of Buddhists across time and place. Experience Buddhism through its scriptures, both relationally as well as academically.",
    "duration": "4 weeks long",
    "topics": [
      "Humanities",
      "History",
      "Religion",
      "Buddhism",
      "Theology"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "5 - 10 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:56.785632Z"
  },
  {
    "title": "CS50: Introduction to Computer Science",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/cs50-introduction-computer-science",
    "level": "intermediate",
    "description": "An introduction to the intellectual enterprises of computer science and the art of programming.",
    "duration": "5 weeks long",
    "topics": [
      "Programming",
      "Computer Science",
      "Data Structures",
      "Algorithms",
      "Sql",
      "Python",
      "Web Development",
      "Css",
      "Html",
      "Javascript"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 219.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "10 - 20 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:57.312933Z"
  },
  {
    "title": "Contemporary China: The People's Republic, Taiwan, and Hong Kong",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/china-part-10-greater-china-today-peoples-republic-taiwan-and-hong-kong",
    "level": "intermediate",
    "description": "Use the case study method to study China from the rise of Deng Xiaoping to the present.",
    "duration": "15 weeks long",
    "topics": [
      "Humanities",
      "Culture",
      "History",
      "Asia"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "1 - 3 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:57.582983Z"
  },
  {
    "title": " Islam Through Its Scriptures",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/islam-through-its-scriptures",
    "level": "intermediate",
    "description": "Learn about the Quran, the central sacred text of Islam, through an exploration of the rich diversity of roles and interpretations in Muslim societies.",
    "duration": "4 weeks long",
    "topics": [
      "Humanities",
      "History",
      "Religion",
      "Theology"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "5 - 10 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:57.840703Z"
  },
  {
    "title": "China’s First Empires and the Rise of Buddhism",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/chinas-first-empires-and-the-rise-of-buddhism",
    "level": "intermediate",
    "description": "Learn about the Qin and Han dynasties, and how Buddhism and ideas of self-realization influenced the medieval period.",
    "duration": "15 weeks long",
    "topics": [
      "Humanities",
      "History",
      "Asia",
      "Buddhism"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "1 - 3 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:58.684454Z"
  },
  {
    "title": "High-Dimensional Data Analysis",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/data-analysis-life-sciences-4-high-dimensional-data-analysis",
    "level": "intermediate",
    "description": "A focus on several techniques that are widely used in the analysis of high-dimensional data.",
    "duration": "4 weeks long",
    "topics": [
      "Data Science",
      "Biostatistics",
      "Data Analysis",
      "Data Visualization",
      "Statistics"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 219.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 4 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:58.956092Z"
  },
  {
    "title": "Shakespeare’s Hamlet: The Ghost",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/shakespeares-hamlet-ghost",
    "level": "intermediate",
    "description": "An exploration of the haunting figure at the heart of one of William Shakespeare’s most famous plays.",
    "duration": "4 weeks long",
    "topics": [
      "Humanities",
      "Shakespeare",
      "Theater",
      "Culture",
      "Literature",
      "Europe",
      "Art & Design"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:59.462536Z"
  },
  {
    "title": "Monteverdi’s L’Orfeo and the Birth of Opera",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/first-nights-monteverdi%E2%80%99s-l%E2%80%99orfeo-and-birth-opera",
    "level": "intermediate",
    "description": "Learn about Claudio Monteverdi’s L’Orfeo, one of the first operas ever written.",
    "duration": "3 weeks long",
    "topics": [
      "Art & Design",
      "Music",
      "Culture"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:11:59.980333Z"
  },
  {
    "title": "CS50's Web Programming with Python and JavaScript",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/cs50s-web-programming-python-and-javascript",
    "level": "intermediate",
    "description": "This course picks up where CS50 leaves off, diving more deeply into the design and implementation of web apps with Python, JavaScript, and SQL using frameworks like Django, React, and Bootstrap.",
    "duration": "12 weeks long",
    "topics": [
      "Programming",
      "Computer Science",
      "Sql",
      "Python",
      "Css",
      "Html",
      "Javascript"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 199.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "6 - 9 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:00.252630Z"
  },
  {
    "title": "Introduction to Data Science with Python",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/introduction-data-science-python",
    "level": "intermediate",
    "description": "Join Harvard University instructor Pavlos Protopapas in this online course to learn how to use Python to harness and analyze data.",
    "duration": "8 weeks long",
    "topics": [
      "Computer Science",
      "Data Science"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 299.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 4 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:00.520102Z"
  },
  {
    "title": "CS50's Computer Science for Business",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/cs50s-computer-science-business",
    "level": "intermediate",
    "description": "This is CS50’s introduction to computer science and tech literacy for business professionals.",
    "duration": "3 weeks long",
    "topics": [
      "Computer Science",
      "Business Intelligence",
      "Information Technology",
      "Data Structures",
      "Programming",
      "Databases",
      "Web Development"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 299.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:00.801418Z"
  },
  {
    "title": "Quantitative Methods for Biology",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/quantitative-methods-biology",
    "level": "intermediate",
    "description": "Learn introductory programming and data analysis in MATLAB, with applications to biology and medicine.",
    "duration": "10 weeks long",
    "topics": [
      "Computer Science",
      "Data Analysis",
      "Medicine",
      "Programming",
      "Biology",
      "Data Science"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 219.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:01.059838Z"
  },
  {
    "title": "Child Protection: Children's Rights in Theory and Practice",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/child-protection-childrens-rights-theory-and-practice",
    "level": "intermediate",
    "description": "Learn how to protect children from violence, exploitation, and neglect through law, policy, and practice in a human rights framework.",
    "duration": "16 weeks long",
    "topics": [
      "Social Sciences",
      "Law",
      "Human Rights"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:01.329384Z"
  },
  {
    "title": "Science &amp; Cooking: From Haute Cuisine to Soft Matter Science (chemistry)",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/science-and-cooking",
    "level": "intermediate",
    "description": "Top chefs and Harvard researchers explore how everyday cooking and haute cuisine can illuminate basic principles in chemistry, physics, and engineering. Learn about food molecules and how chemical reactions can affect food texture and flavor.",
    "duration": "10 weeks long",
    "topics": [
      "Science",
      "Chemistry"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 249.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 3 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:01.589962Z"
  },
  {
    "title": "Super-Earths and Life",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/super-earths-and-life",
    "level": "intermediate",
    "description": "Learn about the Earth, life, and how we can search for life elsewhere in the universe.",
    "duration": "15 weeks long",
    "topics": [
      "Science",
      "Biology"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "5 - 8 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:02.089152Z"
  },
  {
    "title": "Leaders of Learning Essentials",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/leaders-learning-essentials",
    "level": "intermediate",
    "description": "Explore and understand your own theories of learning and leadership.",
    "duration": "5 weeks long",
    "topics": [
      "Education & Teaching",
      "Education",
      "Higher Education",
      "K–12",
      "Museum Studies",
      "Teacher Development",
      "Teaching"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 199.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 3 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:02.368192Z"
  },
  {
    "title": "Data Analysis: Basic Probability and Statistics",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/data-analysis-basic-probability-and-statistics",
    "level": "intermediate",
    "description": "Increase your quantitative reasoning skills through a deeper understanding of probability and statistics, with the engaging “Fat Chance” approach that’s made this course a favorite among learners worldwide.",
    "duration": "7 weeks long",
    "topics": [
      "Mathematics",
      "Probability",
      "Statistics",
      "Data Science"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:02.649217Z"
  },
  {
    "title": "The Path to Happiness: What Chinese Philosophy Teaches Us about the Good Life",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/path-happiness-what-chinese-philosophy-teaches-us-about-good-life",
    "level": "intermediate",
    "description": "Why should we care about Confucius? Explore ancient Chinese philosophy, ethics, and political theory to challenge your assumptions of what it means to be happy, live a meaningful life, and change the world.",
    "duration": "13 weeks long",
    "topics": [
      "Humanities",
      "Wellness",
      "Philosophy",
      "Ethics",
      "Asia",
      "Religion",
      "Buddhism"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 4 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:02.933592Z"
  },
  {
    "title": "Citizen Politics in America: Public Opinion, Elections, Interest Groups, and the Media",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/citizen-politics-america-public-opinion-elections-interest-groups-and-media",
    "level": "intermediate",
    "description": "Learn about the forces in American politics that seek to influence the electorate and shift the political landscape.",
    "duration": "7 weeks long",
    "topics": [
      "Social Sciences",
      "U.S. History",
      "Political Sciences",
      "Government",
      "Public Policy",
      "Humanities"
    ],
    "format": "course",
    "price_type": "free",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": 149.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "2 - 4 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:03.451520Z"
  },
  {
    "title": "The Future of Legal",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/future-legal",
    "level": "intermediate",
    "description": "The Future of Legal provides the tools, knowledge, and practical strategies to navigate how to move forward in changing legal landscape.",
    "duration": "1 week long",
    "topics": [
      "Social Sciences",
      "Law",
      "Leadership",
      "Business"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 14900.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/278A1768.jpg.webp?itok=uwHGopAO",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:04.036994Z"
  },
  {
    "title": "AI Strategy for Business Leaders: From Hype to Impact ",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/ai-strategy-business-leaders-hype-impact-0",
    "level": "intermediate",
    "description": "Leverage new technologies to build value for your organization.",
    "duration": "8 weeks long",
    "topics": [
      "Business",
      "Business Development",
      "Project Management",
      "Artificial Intelligence",
      "Machine Learning",
      "Social Sciences",
      "Computer Science"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 3200.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/possessed-photography-zbLW0FG8XU8-unsplash.jpg.webp?itok=Rqm1u0kn",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:04.301898Z"
  },
  {
    "title": "Core Business Essentials",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/core-business-essentials",
    "level": "intermediate",
    "description": "This 17-week online credential program from Harvard Business School (HBS) Online will teach you the fundamental skills professionals need to succeed today.&nbsp;",
    "duration": "17 weeks long",
    "topics": [
      "Business",
      "Business Intelligence",
      "Strategy",
      "Business Analysis",
      "Business Development",
      "Accounting",
      "Finance",
      "Career Development",
      "Professional Development",
      "Self-Improvement",
      "Data Analysis",
      "Statistics"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 2650.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/laptop_FB_size.png.webp?itok=NLEnLM7D",
    "time_commitment": "5 - 8 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:04.573060Z"
  },
  {
    "title": "Introduction to Neural Networks and Deep Learning with Python",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/introduction-neural-networks-and-deep-learning-python",
    "level": "intermediate",
    "description": "Build practical deep learning skills for Python-savvy professionals.",
    "duration": "8 weeks long",
    "topics": [
      "Computer Science",
      "Artificial Intelligence",
      "Deep Learning",
      "Machine Learning",
      "Natural Language Processing",
      "Neural Networks",
      "Data Science"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 299.0,
    "currency": "USD",
    "certificate_price": 299.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/edX-LOGO.svg",
    "time_commitment": "3 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:04.851927Z"
  },
  {
    "title": "Negotiation and Leadership",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/negotiation-and-leadership-10",
    "level": "intermediate",
    "description": "Six esteemed PON faculty members have come together to lead our in-person 3-day program. The program curriculum is packed with negotiation strategies and best practices designed to help you get results.",
    "duration": "6 days long",
    "topics": [
      "Business",
      "Negotiation"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 5497.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/N%26L-image-for-Portal_7.jpg.webp?itok=Yn065aI2",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:05.386890Z"
  },
  {
    "title": "Changing the Game: Negotiation and Competitive Decision-Making",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/changing-game-negotiation-and-competitive-decision-making",
    "level": "intermediate",
    "description": "Develop the psychological insights and practical skills needed to negotiate more effectively and make better decisions.",
    "duration": "6 days long",
    "topics": [
      "Business",
      "Negotiation",
      "Leadership",
      "Management",
      "Networking",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 16000.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2025-06/hbs-dm-program-1024x683%20%281%29.jpg.webp?itok=-rF_8xzb",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:06.177073Z"
  },
  {
    "title": "The Consultant's Toolkit",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/consultants-toolkit-0",
    "level": "intermediate",
    "description": "Refine your consulting abilities through proven techniques to improve organizational effectiveness.",
    "duration": "6 weeks long",
    "topics": [
      "Business",
      "Entrepreneurship",
      "Business Development",
      "Career Development",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 3200.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/christina-wocintechchat-com-HG9M8M29Ig4-unsplash.jpg.webp?itok=MCA7p1cp",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:06.779621Z"
  },
  {
    "title": "Data Science and AI Principles - October 2026",
    "provider": "Harvard Harvard University",
    "url": "https://pll.harvard.edu/course/data-science-and-ai-principles/2026-10",
    "level": "intermediate",
    "description": "View All Courses",
    "duration": "4 weeks long",
    "topics": [
      "Business",
      "Career Development",
      "Professional Development",
      "Self-Improvement",
      "Data Science"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/datascienceprinciples_resized.png.webp?itok=NVR1ihgA",
    "time_commitment": "4 - 5 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:07.911514Z"
  },
  {
    "title": "Audit and Risk Committees",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/audit-and-risk-committees",
    "level": "intermediate",
    "description": "Explore best practices for aligning financial reporting with corporate strategy. Help your company operate more effectively in today’s demanding market and regulatory environment.",
    "duration": "3 days long",
    "topics": [
      "Business",
      "Finance",
      "Leadership",
      "Management",
      "Networking",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 8250.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/audit-committees-new-era-governance.jpg.webp?itok=KvooIvmF",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:08.515856Z"
  },
  {
    "title": "Driving Corporate Performance",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/driving-corporate-performance",
    "level": "intermediate",
    "description": "Master the art of aligning structures, systems, talent, and processes to execute a winning strategy. Leverage powerful systems for performance measurement and management control to chart a path toward short and long-term success.",
    "duration": "6 days long",
    "topics": [
      "Business",
      "Leadership",
      "Management",
      "Networking",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 16250.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/driving-corporate-performance.jpg.webp?itok=Dm4PXPTq",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:09.745175Z"
  },
  {
    "title": "Aligning Strategy and Sales",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/aligning-strategy-and-sales",
    "level": "intermediate",
    "description": "Close the gap between your strategic priorities and sales performance. Create company-wide alignment that boosts revenue and long-term success.",
    "duration": "6 days long",
    "topics": [
      "Business",
      "Leadership",
      "Management",
      "Marketing",
      "Networking",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 16250.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/aligning-strategy-sales.jpg.webp?itok=IzE4B2bK",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:10.270218Z"
  },
  {
    "title": "Ethical Leadership",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/ethical-leadership-0",
    "level": "intermediate",
    "description": "Develop the ability to lead through challenging dilemmas and competing values to promote ethical decision-making.",
    "duration": "self-paced",
    "topics": [
      "Business",
      "Leadership",
      "Management",
      "Career Development",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 1570.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "Online Live",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/cowomen-pd5FVvQ9-aY-unsplash.jpg.webp?itok=kHIojOYT",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:10.791653Z"
  },
  {
    "title": "Stretching and Flexibility Exercises",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/stretching-and-flexibility-exercises",
    "level": "intermediate",
    "description": "Doing simple stretching exercises just two or three times a week can dramatically help you increase flexibility, improve balance, and relieve pain caused by muscle and joint stiffness.",
    "duration": "2 weeks long",
    "topics": [
      "Health & Medicine",
      "Healthcare"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 30.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2025-04/GettyImages-2192441110.jpg.webp?itok=_7JuPCvo",
    "time_commitment": "2 - 6 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:12.154793Z"
  },
  {
    "title": "Healthy Feet",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/healthy-feet",
    "level": "intermediate",
    "description": "A lot can go wrong with your feet, from sprains,  fractures, and fungal infections to bunions, plantar fasciitis, and peripheral neuropathy, among other issues. Learn how to treat the full range of foot conditions—and how to prevent them. ",
    "duration": "2 weeks long",
    "topics": [
      "Health & Medicine",
      "Healthcare"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 30.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2025-04/GettyImages-512698489.jpg.webp?itok=GaDZ0WUJ",
    "time_commitment": "2 - 6 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:12.675827Z"
  },
  {
    "title": "Leadership in Corporate Counsel",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/leadership-corporate-counsel-0",
    "level": "intermediate",
    "description": "The Leadership in Corporate Counsel program offers in-house leaders insights into the challenges they face and the frameworks, concepts, and tools they need to succeed in their increasingly complicated roles.&nbsp;",
    "duration": "1 week long",
    "topics": [
      "Business",
      "Leadership",
      "Law",
      "Social Sciences"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 14900.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/HarvardLaw046.JPG.webp?itok=OLIe6hdm",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:13.186173Z"
  },
  {
    "title": "Health and Wellness: Designing a Sustainable Nutrition Plan",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/health-and-wellness-designing-sustainable-nutrition-plan",
    "level": "intermediate",
    "description": "This is a Harvard Medical School online executive education program designed to give you the tools and confidence to create personalized healthy living plans for clients, patients, friends and yourself.",
    "duration": "2 weeks long",
    "topics": [
      "Health & Medicine",
      "Health",
      "Medicine",
      "Healthcare",
      "Nutrition",
      "Wellness"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 3150.0,
    "currency": "USD",
    "certificate_price": 2750.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/GettyImages-1355049920.jpg.webp?itok=yyyBxUGl",
    "time_commitment": "4 - 6 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:13.452695Z"
  },
  {
    "title": "Strategies for Leading Successful Change Initiatives: Mastery Session",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/strategies-leading-successful-change-initiatives-mastery-session-0",
    "level": "intermediate",
    "description": "Master the key skills requisite to lead your teams through critical change initiatives. You'll learn to build trust, gain buy-in, and create inspiration and innovation that will lead to your team's success.",
    "duration": "self-paced",
    "topics": [
      "Business",
      "Leadership",
      "Management",
      "Strategic Management",
      "Career Development",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 4200.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/pexels-rebrand-cities-1367276.jpg.webp?itok=GyW8Ez1B",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:14.037807Z"
  },
  {
    "title": "The Herbert Benson, MD Course in Mind Body Medicine",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/herbert-benson-md-course-mind-body-medicine-2",
    "level": "intermediate",
    "description": "Mind Body Medicine teaches evidence-based interventions that enhance patient care and clinical outcomes.",
    "duration": "2 weeks long",
    "topics": [
      "Health & Medicine",
      "Medicine",
      "Healthcare",
      "Mental Health"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 975.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-PersonOnline Live",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2026-08/Mind%20Body%202026%20Hero3.jpg.webp?itok=hAu138xj",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:14.559834Z"
  },
  {
    "title": "HMX Biochemistry",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/hmx-biochemistry",
    "level": "intermediate",
    "description": "Learn foundational concepts in biochemistry and gain a new appreciation for how this field applies to human health and disease.",
    "duration": "self-paced",
    "topics": [
      "Health & Medicine",
      "Health",
      "Medicine",
      "Diseases",
      "Healthcare",
      "Biochemistry"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 1025.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/hmx_0_0.svg",
    "time_commitment": "3 - 6 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:15.106359Z"
  },
  {
    "title": "Building a Life of Wellness",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/building-life-wellness",
    "level": "intermediate",
    "description": "The Building a Life of Wellness: The Science of Fostering Happiness and Health Span program blends the latest research on well-being with evidence-based techniques to cultivate and sustain long-term relationships, which supports health and wellness.",
    "duration": "self-paced",
    "topics": [
      "Health & Medicine",
      "Healthcare"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 2350.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2024-12/Building_0.jpg.webp?itok=PK3CEXzK",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:15.610248Z"
  },
  {
    "title": "Strategy: Building and Sustaining Competitive Advantage - June 2027",
    "provider": "Harvard Harvard University",
    "url": "https://pll.harvard.edu/course/strategy-building-and-sustaining-competitive-advantage/2027-06",
    "level": "intermediate",
    "description": "View All Courses",
    "duration": "6 days long",
    "topics": [
      "Business",
      "Leadership",
      "Management",
      "Strategic Management",
      "Networking",
      "Professional Development"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "In-Person",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/strategy-building-sustaining-competitive-advantage.jpg.webp?itok=N508_bTR",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:16.135929Z"
  },
  {
    "title": "Novel Therapies for Chronic Inflammation, Autoimmunity, and Allergy",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/novel-therapies-chronic-inflammation-autoimmunity-and-allergy",
    "level": "intermediate",
    "description": "Learn how the immune system is harnessed to treat inflammation.",
    "duration": "8 weeks long",
    "topics": [
      "Health & Medicine",
      "Health",
      "Medicine",
      "Diseases",
      "Disorders",
      "Healthcare",
      "Immunology",
      "Nursing",
      "Biology",
      "Biotechnology",
      "Microbiology",
      "Molecular Biology",
      "Science"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 1025.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/platform/logo/hmx_0_0.svg",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:16.708864Z"
  },
  {
    "title": "The Science of Leadership: The Brain, Resilience, and Mindfulness",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/science-leadership-brain-resilience-and-mindfulness",
    "level": "intermediate",
    "description": "Navigate rising complexity and uncertainty by developing the mental clarity, emotional resilience, and composure needed to lead teams effectively.",
    "duration": "2 weeks long",
    "topics": [
      "Social Sciences",
      "Wellness",
      "Leadership",
      "Social Science",
      "Health & Medicine"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 2950.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online Live",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2026-02/ScienceOfLeadership728x523%20%281%29.jpg.webp?itok=i8owOUjv",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:17.228101Z"
  },
  {
    "title": "How to Bring the Real You to Work: Authenticity, Connection, and Identity",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/how-bring-real-you-work-authenticity-connection-and-identity",
    "level": "intermediate",
    "description": "Taught by Harvard Professor Henry Louis Gates, Jr. with insights from actor and singer Cynthia Erivo",
    "duration": "self-paced",
    "topics": [
      "Business",
      "Career Development",
      "Coaching",
      "Communication Skills",
      "Exercising Influence",
      "Networking",
      "Performance Management",
      "Professional Development",
      "Self-Improvement"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 175.0,
    "currency": "USD",
    "certificate_price": 175.0,
    "platform": "Harvard Online",
    "pace": "Self-paced",
    "modality": "Online",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2025-10/PowerSkills_Gates_Erivo.png.webp?itok=ijNmOd0R",
    "time_commitment": "2 - 3 total hours",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:17.767514Z"
  },
  {
    "title": "Strategic Leadership: Enhancing Your Personal Effectiveness - May 2027",
    "provider": "Harvard Harvard University",
    "url": "https://pll.harvard.edu/course/strategic-leadership-enhancing-your-personal-effectiveness/2027-05",
    "level": "intermediate",
    "description": "View All Courses",
    "duration": "2 weeks long",
    "topics": [
      "Social Sciences",
      "Government",
      "Public Leadership",
      "Public Management",
      "Public Policy"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": null,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "OnlineOnline Live",
    "language": "Course LanguageEnglish",
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/new%20sep.jpeg.webp?itok=VLTtciOt",
    "time_commitment": "25 - 35 hours per week",
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:18.292532Z"
  },
  {
    "title": "Collaborative Co-Teaching: Engaging Learners across Health Care Professions",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/collaborative-co-teaching-engaging-learners-across-health-care-professions",
    "level": "intermediate",
    "description": "Learners will come away from this course with practical methods to start a Collaborative Co-Teaching initiative at their own institution.",
    "duration": "self-paced",
    "topics": [
      "Health & Medicine",
      "Healthcare"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 275.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "Online Live",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/2024-07/collabortive_co_teaching_720.png.webp?itok=8DnDGRHU",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:18.808951Z"
  },
  {
    "title": "Foundations of Clinical Research",
    "provider": "Harvard Harvard Online",
    "url": "https://pll.harvard.edu/course/foundations-clinical-research",
    "level": "intermediate",
    "description": "This&nbsp;Harvard Medical School&nbsp;six-month,&nbsp;application-based certificate program&nbsp;provides the essential skill&nbsp;sets and fundamental knowledge required to begin or expand your clinical research career.",
    "duration": "self-paced",
    "topics": [
      "Health & Medicine",
      "Health",
      "Medicine",
      "Healthcare",
      "Health Research",
      "Medical Research"
    ],
    "format": "course",
    "price_type": "paid",
    "price_amount": 9200.0,
    "currency": "USD",
    "certificate_price": null,
    "platform": "Harvard Online",
    "pace": "Instructor-led",
    "modality": "Online Live",
    "language": null,
    "image_url": "https://pll.harvard.edu/sites/default/files/styles/16_9_medium/public/course/FCR_0.jpg.webp?itok=j-wG6TqD",
    "time_commitment": null,
    "source": "harvard_pll",
    "scraped_at": "2026-08-22T11:12:19.087643Z"
  }
]
